

SELECT E.FIRST_NAME      AS NOME,
       E.SALARY          AS SALARIO,
       E.DEPARTMENT_ID   AS "DEPT COD",
       D.DEPARTMENT_NAME AS "DEPT NOME",
       B.SAL_AVG,
       S.SOMA
  FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
  INNER JOIN
     (SELECT ROUND(AVG(SALARY)) AS SAL_AVG,
               DEPARTMENT_ID
          FROM EMPLOYEES
      GROUP BY DEPARTMENT_ID) B
ON(E.DEPARTMENT_ID = B.DEPARTMENT_ID)
AND E.SALARY > B.SAL_AVG
  INNER JOIN 
     (SELECT SUM(SALARY) AS SOMA,
             DEPARTMENT_ID
        FROM EMPLOYEES
        GROUP BY DEPARTMENT_ID) S
ON(E.DEPARTMENT_ID = S.DEPARTMENT_ID);